// Generated by https://quicktype.io

export interface IAlbum {
  href: string;
  items: IAlbumItem[];
  limit: number;
  next: string;
  offset: number;
  previous: string;
  total: number;
}

export interface IAlbumItem {
  album_type: string;
  available_markets: null[];
  external_urls: string[];
  href: string;
  id: string;
  images: null[];
  name: string;
  type: string;
  uri: string;
}
