// Generated by https://quicktype.io

export interface IArtists {
  artists: IArtistElement[];
}

export interface IArtistElement {
  external_urls: ExternalUrls;
  followers: ExternalUrls;
  genres: null[];
  href: string;
  id: string;
  images: IArtistImage[];
  name: string;
  popularity: number;
  type: string;
  uri: string;
}

export interface ExternalUrls {}

export interface IArtistImage {
  height: number;
  width: number;
  url: string;
}
