// Generated by https://quicktype.io
import { IImage } from './Image.model';

export interface IArtists {
  artists: IArtistElement[];
}

export interface IArtistElement {
  external_urls: ExternalUrls;
  followers: ExternalUrls;
  genres: null[];
  href: string;
  id: string;
  images: IImage[];
  name: string;
  popularity: number;
  type: string;
  uri: string;
}

export interface ExternalUrls {}
